### ISSUE TITLE
FlutterBlue can't scan while app is in the background

### ISSUE THREAD

**Issue by SebastianKotewitz** [DTUFeedme/feedme-mobile#6]
FlutterBlue does not find any devices when scanning while the app is not in the foreground or when the screen is off.
[This](https://github.com/pauldemarco/flutter_blue/pull/210) PR on the FlutterBlue git [contains](https://github.com/rmawatson/flutter_blue/tree/background_feature) a fix to this issue, but it is several pulls behind Flutter Blue. We can try merging these and using the result as our own version of FlutterBlue.

**Comment by SebastianKotewitz** [comment]
This issue could be android/Samsung related.
Bluetooth scans work in all cases, but no results are found while the screen is off. The results are found even when the phone is locked with the screen on, and they are also found while in other apps.
After attempting to merge the PR mentioned above, and even trying the old version of FlutterBlue with the changes made directly from the PR git, nothing changed the behavior of FlutterBlue when the screen was off.

According to [this link](https://stackoverflow.com/questions/48077690/ble-scan-is-not-working-when-screen-is-off-on-android-8-1-0), this happens to unfiltered scans from Android 8.1.0 onward. The link mentions putting an empty filter on the scan, but even after modifying the FlutterBlue android file and adding an empty filter, it didn't work with the screen locked. This could be looked into further if nothing else seems to work.

FlutterBlue supports filtering by serviceUUID, but it doesn't seem that our beacons have a serviceUUID in the correct place for it to register. I found hue lamps have one, but I have not tested filtering on their serviceUUID. FlutterBlues device filter does not work as of v0.7.2

**Comment by sasp1** [comment]
I'm going to try with native code to see if that works 👍

**Comment by sasp1** [comment]
Seems to work fine in native android, even when app is closed (swiped off in app tray) and screen is turned off. Testing on a OnePlus 5T

**Comment by SebastianKotewitz** [comment]
It seems to be scanning BLE devices and printing results continuously when the app is open, but pauses when the screen is turned off on S8. The printing stops completely when the app is swiped away, so I may be using the demo wrong.

**Comment by sasp1** [comment]
You have to use Logcat to get the logs after you close the app. But sounds like it is a samsung issue then. :/

**Comment by sasp1** [comment]
Oh wait. I just realized that you might actually be using the demo wrong. You have to swipe the app off and/or close the screen before the 10 second delay. And then see if the scheduled task still works and start printing beacon signals. 
If I start the scanning and then close the app then it also stop the scanning on my OnePlus but I think that is to be expected

**Comment by sasp1** [comment]
I found out that even Oneplus will in some cases kill the background process when the app is closed. It turns out, that Oneplus and Samsung has one of the most severe background limits. https://dontkillmyapp.com/
However, if you actively disable battery optimization for the app then it still works. We might have to promt the user to do so.

**Comment by SebastianKotewitz** [comment]
After following those instructions, it now works when swiping the app away. The scanning is still paused (not stopped) when turning the screen off.
